# Generated by Django 5.2.1 on 2025-08-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', '-created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_to',
            new_name='created_at',
        ),
    ]
